input(type="imudp" port="514")  # Listen on UDP port 514
set $.loglevel = re_extract($msg, "^([A-Z]+):", 0, 0, "NONE");

#template(name="MySQLTemplate" type="string" string="%timestamp% %syslogseverity-text% %syslogfacility-text% %msg% %programname% %fromhost-ip% %$.loglevel% \n")

template(name="MySQLTemplate" type="string" option.sql="on" string="INSERT INTO logs (level, timestamp, severity, facility, programname, host, message) VALUES ('%$.loglevel%', '%timegenerated:::date-pgsql%', '%syslogseverity-text%', '%syslogfacility-text%', '%programname%', '%fromhost-ip%', '%msg%');")


# Write the extracted data to MySQL
#action(type="ommysql" server="localnet_host" database="syslog" user="sysloguser" password="password" template="MySQLTemplate")
action(type="ommysql"
       server="127.0.0.1"
       db="loxioam"
       uid="oamuser"
       pwd="CHANGE_ME"
       template="MySQLTemplate")