$ModLoad imfile    # Load the imfile input module

# Poll the log file every 10 seconds
$InputFilePollInterval 10
$InputFileName  /var/log/loxioam.log
$InputFileTag loxioam-access
$InputFileStateFile stat-loxioam-access
$InputFileSeverity info
$InputFileFacility local0
$InputRunFileMonitor

if $programname == 'loxioam-access' then @127.0.0.1:514;