$ModLoad imfile    # Load the imfile input module

# Poll the log file every 10 seconds
$InputFilePollInterval 10
$InputFileName  /var/log/loxilbloxilb-oem.log
$InputFileTag loxilb
$InputFileStateFile stat-loxilb
$InputFileSeverity info
$InputFileFacility local0
$InputRunFileMonitor

# Replace LOG_SERVER_HOST with your central rsyslog collector address.
if $programname == 'loxilb' then @LOG_SERVER_HOST:514;
