package models

import "time"

// User represents a user in the system.
// License management is handled through the ActiveLicense model.
type User struct {
	ID       int    `json:"id"`
	Username string `json:"username"`
	// Password hash is never serialized in API responses. Requests use
	// dedicated DTOs (LoginRequest/CreateUserRequest), so `json:"-"` here only
	// affects responses — it stops GetUsers/GetMe from leaking the hash.
	Password  string    `json:"-"`
	Role      string    `json:"role"` // "admin", "operator" or "viewer"
	Email     string    `json:"email"`
	CreatedAt time.Time `json:"created_at"`
}

// LoxiLBInstance represents a LoxiLB instance.
type LoxiLBInstance struct {
	ID          int       `json:"id"`
	Name        string    `json:"name"`
	Host        string    `json:"host"`
	Port        string    `json:"port"`
	Protocol    string    `json:"protocol"`
	Description string    `json:"description"`
	Version     string    `json:"version"`
	ApiEndpoint string    `json:"api_endpoint"`
	Cimage      string    `json:"cimage"`
	Ctag        string    `json:"ctag"`
	IsActive    bool      `json:"is_active"`
	CreatedAt   time.Time `json:"created_at"`
}

// APIToken represents an API token.
type APIToken struct {
	TokenID    int       `json:"token_id"`
	TokenValue string    `json:"token_value"`
	UserID     string    `json:"user_id"`
	Scopes     []string  `json:"scopes"`
	ExpiresAt  time.Time `json:"expires_at"`
	CreatedAt  time.Time `json:"created_at"`
}

// LogEntry represents a log entry in the Logs table.
type LogEntry struct {
	ID          int       `json:"id"`
	Level       time.Time `json:"level"`
	Timestamp   time.Time `json:"timestamp"`
	Severity    int       `json:"severity"`
	Facility    int       `json:"facility"`
	Programname string    `json:"programname"`
	Host        string    `json:"host"`
	Message     string    `json:"message"`
	CreatedAt   time.Time `json:"created_at"`
}

type LoginRequest struct {
	Username string `json:"username" binding:"required"`
	Password string `json:"password" binding:"required"`
}

type LoxiLBInstanceRequest struct {
	Name        string `json:"name" binding:"required"`
	Host        string `json:"host" binding:"required"`
	Port        string `json:"port" binding:"required"`
	Protocol    string `json:"protocol" binding:"required"` // "http" or "https"
	Description string `json:"description"`
	Version     string `json:"version"`
	Cimage      string `json:"cimage" binding:"required"`
	Ctag        string `json:"ctag" binding:"required"`
	IsActive    *bool  `json:"is_active,omitempty"` // Optional, defaults to true
}

// CreateUserRequest represents a request to create a new user
type CreateUserRequest struct {
	Username string `json:"username" binding:"required"`
	Email    string `json:"email" binding:"required"`
	Password string `json:"password" binding:"required"`
	Role     string `json:"role,omitempty"` // Optional: Admin can set role (defaults to "user")
}

type UserIdResponse struct {
	ID int `json:"id"`
}

// LoginResponse represents the response returned after a successful login.
type LoginResponse struct {
	ID    int    `json:"id"`
	Token string `json:"token"`
}

// MessageResponse represents a simple message response.
type MessageResponse struct {
	Message string `json:"message"`
}

// SuccessResponse represents a simple message response.
type SuccessResponse struct {
	Message string `json:"message"`
}

// SuccessResponse represents a simple message response.
type SuccessPostResponse struct {
	// code
	Code int64 `json:"code,omitempty"`
	// message
	Message string `json:"message,omitempty"`
}

// ErrorResponse represents the error response returned by the API.
type ErrorResponse struct {
	// code
	Code int32 `json:"code,omitempty"`
	// details
	Details string `json:"details,omitempty"`
	// fields
	Fields []string `json:"fields"`
	// message
	Message string `json:"message,omitempty"`
	// result
	Result string `json:"result,omitempty"`
	// sub code
	SubCode int32 `json:"sub-code,omitempty"`
}

// HealthCheckResponse represents the health check response.
type HealthCheckResponse struct {
	Status string `json:"status"`
}

// =================== Log Monitoring Models ===================

type LogResponse struct {
	Logs []string `json:"logs"`
}

type LogArchivesResponse struct {
	// List of log archive filenames.
	Archives []string `json:"archives"`
}

// =================== Alerts & Acknowledgment Models ===================
// Alert represents an alert generated by the system.
type Alert struct {
	ID         int        `json:"id"`
	InstanceID int        `json:"instance_id"`
	Type       string     `json:"type"`     // DB_DISCONNECT, API_UNREACHABLE, HIGH_CPU, MEMORY_LEAK.
	Severity   string     `json:"severity"` // INFO, WARNING, CRITICAL
	Message    string     `json:"message"`
	CreatedAt  time.Time  `json:"created_at"`
	ResolvedAt *time.Time `json:"resolved_at,omitempty"` // Nullable if not resolved
}

// Request to create an alert
type CreateAlertRequest struct {
	InstanceID int    `json:"instance_id" binding:"required"`
	Type       string `json:"type" binding:"required"`
	Severity   string `json:"severity" binding:"required"`
	Message    string `json:"message" binding:"required"`
}

// Response for alert creation
type CreateAlertResponse struct {
	Status  string `json:"status"`
	AlertID int    `json:"alert_id"`
}

// Acknowledgment represents an acknowledgment for an alert.
type Acknowledgment struct {
	ID      int       `json:"id"`
	AlertID int       `json:"alert_id"`
	UserID  int       `json:"user_id"`
	AckTime time.Time `json:"ack_time"`
}

// Request to acknowledge an alert
type AcknowledgeRequest struct {
	UserID int `json:"user_id" binding:"required"`
}

// Response after acknowledging an alert
type AcknowledgeResponse struct {
	Status  string    `json:"status"`
	AlertID int       `json:"alert_id"`
	AckTime time.Time `json:"ack_time"`
}

// UpdateFirmwareRequest represents the request body for updating firmware of a LoxiLB instance.
type UpdateFirmwareRequest struct {
	Cimage *string `json:"cimage" binding:"required" example:"ghcr.io/loxilb-io/loxilb"`
	Ctag   *string `json:"ctag" binding:"required" example:"v0.9.8"`

	// Optional fields
	Description *string `json:"description,omitempty" example:"Updated firmware description"`
	Version     *string `json:"version,omitempty" example:"v0.9.8"`
}

// =================== Pagination Models ===================

// PaginationMeta represents pagination metadata
type PaginationMeta struct {
	Page       int  `json:"page"`        // Current page number
	Limit      int  `json:"limit"`       // Number of items per page
	TotalCount int  `json:"total_count"` // Total number of items
	TotalPages int  `json:"total_pages"` // Total number of pages
	HasNext    bool `json:"has_next"`    // Whether there's a next page
	HasPrev    bool `json:"has_prev"`    // Whether there's a previous page
}

// PaginatedAlertsResponse represents a paginated response for alerts
type PaginatedAlertsResponse struct {
	Data       []Alert        `json:"data"`       // The alert data
	Pagination PaginationMeta `json:"pagination"` // Pagination metadata
}

// EnhancedLoginResponse is the successful login response body.
type EnhancedLoginResponse struct {
	ID    int    `json:"id"`
	Token string `json:"token"`
}

// LoginAttempt represents a failed login attempt for tracking and lockout purposes
type LoginAttempt struct {
	ID           int        `json:"id"`
	Username     string     `json:"username"`
	ClientIP     string     `json:"client_ip"`
	FailedCount  int        `json:"failed_count"`
	LastFailedAt time.Time  `json:"last_failed_at"`
	BlockedUntil *time.Time `json:"blocked_until,omitempty"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `json:"updated_at"`
}
