apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- mysql-secret.yaml
- mysql-configmap.yaml
- mysql-init-configmap.yaml
- mysql-pvc.yaml
- mysql-deployment.yaml
- mysql-service.yaml
- oam-loxilb-configmap.yaml
- oam-loxilb-secret.yaml
- oam-loxilb-deployment.yaml
- oam-loxilb-service.yaml
- oam-loxilb-ingress.yaml

commonLabels:
  app.kubernetes.io/name: oam-loxilb
  app.kubernetes.io/version: v0.9.8.7
  app.kubernetes.io/component: oam-system
  app.kubernetes.io/protocol: http

images:
- name: oam-loxilb
  newTag: latest