-- Submitting whole-Appliance operations (contract appliance-ops/v1alpha1):
-- one active operation per installation, the one-use authorization challenge
-- for destructive operations, and the audit trail.

-- Whether the operation can still be cancelled, as the host adapter last
-- reported it. Before submission OAM decides and this column is not consulted.
ALTER TABLE appliance_operations
    ADD COLUMN cancellable BOOLEAN NOT NULL DEFAULT FALSE;

-- One active operation per installation. RECOVERY_REQUIRED is included on
-- purpose: nothing else may run on an installation whose state is unknown.
-- PLANNED is not: any number of plans may exist side by side.
CREATE UNIQUE INDEX uk_appliance_operations_one_active
    ON appliance_operations (installation_id)
    WHERE state IN ('AWAITING_AUTHORIZATION', 'QUEUED', 'RUNNING', 'VERIFYING',
                    'COMPENSATING', 'RECOVERY_REQUIRED');

-- A challenge proves that a specific user, in a specific session, re-entered
-- their password to authorize one specific plan. Only its SHA-256 is stored;
-- the value itself is returned once and never written anywhere.
CREATE TABLE appliance_challenges (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    challenge_hash  TEXT        NOT NULL,
    operation_id    UUID        NOT NULL REFERENCES appliance_operations (id) ON DELETE CASCADE,
    actor_user_id   INTEGER     NOT NULL,
    -- The jti of the token that authorized. A token is a session; a
    -- challenge issued in one is useless in another.
    session_id      TEXT        NOT NULL,
    plan_hash       TEXT        NOT NULL,
    installation_id TEXT        NOT NULL,
    action          TEXT        NOT NULL,
    expires_at      TIMESTAMPTZ NOT NULL,
    consumed_at     TIMESTAMPTZ,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uk_appliance_challenges_hash UNIQUE (challenge_hash)
);

CREATE INDEX idx_appliance_challenges_operation ON appliance_challenges (operation_id);

-- Append-only record of everything that happened to an operation and who
-- caused it. `detail` holds only fields the application declares; it never
-- contains passwords, challenges, tokens, archive contents or key material.
-- No foreign key: the record must outlive the operation and the user.
CREATE TABLE appliance_audit (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    operation_id   UUID        NOT NULL,
    event          TEXT        NOT NULL,
    actor_user_id  INTEGER,
    actor_username TEXT        NOT NULL DEFAULT '',
    request_id     TEXT        NOT NULL DEFAULT '',
    source_ip      TEXT        NOT NULL DEFAULT '',
    old_state      TEXT        NOT NULL DEFAULT '',
    new_state      TEXT        NOT NULL DEFAULT '',
    detail         JSONB       NOT NULL DEFAULT '{}',
    created_at     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_appliance_audit_operation ON appliance_audit (operation_id, id);
