apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- postgres-secret.yaml
- postgres-init-configmap.yaml
- postgres-service.yaml
- oam-loxilb-configmap.yaml
- oam-loxilb-secret.yaml
- ssl-secret.yaml
- oam-loxilb-service.yaml
- oam-loxilb-ingress.yaml
- postgres-deployment.yaml
- oam-loxilb-deployment.yaml
- postgres-pvc.yaml

images:
- name: oam-loxilb
  newTag: latest