apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  namespace: oam-loxilb
  labels:
    app: mysql
    component: database
spec:
  selector:
    app: mysql
  ports:
  - port: 3306
    targetPort: 3306
    protocol: TCP
    name: mysql
  type: ClusterIP