apiVersion: v1
kind: ConfigMap
metadata:
  name: oam-loxilb-config
  namespace: oam-loxilb
data:
  DB_HOST: "postgres-service.oam-loxilb.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "loxioam"
  TOKEN_EXPIRATION: "1440"
  SERVER_PORT: "443"