apiVersion: v1
kind: ConfigMap
metadata:
  name: oam-loxilb-config
  namespace: oam-loxilb
data:
  DB_HOST: "mysql-service.oam-loxilb.svc.cluster.local"
  DB_PORT: "3306"
  DB_NAME: "loxioam"
  TOKEN_EXPIRATION: "1440"
  SERVER_PORT: "443"
  GOOGLE_REDIRECT_URL: "https://localhost:443/oam/oauth/google/callback"
  GITHUB_REDIRECT_URL: "https://localhost:443/oam/oauth/github/callback"
  FACEBOOK_REDIRECT_URL: "https://localhost:443/oam/oauth/facebook/callback"