apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oam-loxilb-ingress
  namespace: oam-loxilb
  labels:
    app: oam-loxilb
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: oam-loxilb.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: oam-loxilb-service
            port:
              number: 8080